import { ConvertActionBindingResult } from '@angular/compiler/src/compiler_util/expression_converter';
import { Component, OnInit } from '@angular/core';
import { NgForm,FormGroup,FormBuilder,Validators } from '@angular/forms';
import{StudentInfoModule} from 'src/app/Modules/student-info/student-info.module';
import{StudentInfoService} from 'src/app/Services/student-info.service';
import {Router} from '@angular/router';
import {QusnInfoService} from 'src/app/Services/qusn-info.service';
import * as forge from 'node-forge';


@Component({
  selector: 'app-register-page',
  templateUrl: './register-page.component.html',
  styleUrls: ['./register-page.component.css']
})
export class RegisterPageComponent implements OnInit {
  model:any=[];
  siteKey:string;
  buttondiv:boolean=true;
  AboutUs:boolean=false;
  protected aFormGroup: FormGroup;
  svc:StudentInfoService;
  stud:StudentInfoModule=
  {
    StudentId:1,
    Name:'string',
    Mobile:'string',
    Email:'string',
    DOB:   new Date("10/12/2020"),
    College:'string',
    City:'string',
    State:'string',
    Qualifacton:'string',
    YearOfCompletion:'string',
    Password:'string',
    LastLogin:new Date("10/12/2020"),
    OTP:null

  };
  stateInfo: any[] = [];
  state:any;
  countryInfo: any[] = [];
  cityInfo: any[] = [];

  publicKey: string = `-----BEGIN PUBLIC KEY-----
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYtmHLSiliYtZQb1yvBeqqE01T
  hUYiuV3Qex2ril2hL9AEG3oI7b1R8IAoppcojjX0wnccKUeSryiuD/I8LC5jAErx
  RKXklxgZ2LxLoVwVczTfrev1noRsFS6J2dPSw183C3UVd7WQTxpcxjVf1j2rxAvS
  SUgxQwlCJiDU9M6CTQIDAQAB
  -----END PUBLIC KEY-----`;

//initiate some value



  constructor(svc:StudentInfoService,private router:Router,private service:QusnInfoService) { this.svc=svc;
  this.siteKey='6LfOKKkaAAAAAF1urn3o790SHYWiKPDD4tVI3l-7'//key Generated by  google captcha of version-2
  }
  ngOnInit(): void {

    this.getCountries();

  }

  getCountries(){
    this.service.allCountries().
    subscribe(
      data2 => {
        this.countryInfo=data2.Countries;
        //console.log('Data:', this.countryInfo);
      },
      err => console.log(err),
      () => console.log('complete')
    )
  }

  onChangeCountry() {
    this.stateInfo=this.countryInfo[100].States;
    // this.cityInfo=this.stateInfo[10].Cities;
    console.log(this.stateInfo);
  }

  onChangeState(stateValue) {
    this.cityInfo=this.stateInfo[stateValue].Cities;
    console.log(this.cityInfo);
  }

  RegData(Reg:NgForm):void
{
  var state = this.stateInfo[Reg.value.state].StateName;
  console.log(Reg.value);
  this.stud.Name=Reg.value.name;
  this.stud.Mobile=Reg.value.mobno;
  this.stud.Email=Reg.value.email;
  this.stud.DOB=Reg.value.dob;
  this.stud.College=Reg.value.clg;
  this.stud.City=Reg.value.city;
  this.stud.State=state;
  this.stud.Qualifacton=Reg.value.qual;
  this.stud.YearOfCompletion=Reg.value.yoc;

  var rsa = forge.pki.publicKeyFromPem(this.publicKey);
  var encryptedPassword = window.btoa(rsa.encrypt(Reg.value.pass));
  this.stud.Password=encryptedPassword;

  this.svc.ChkEmail(this.stud.Email).subscribe((data:string)=>{
    if(data == "success") {
      alert("Email ID already in use. Please use another ID");
    }
    else{
      this.svc.RegisterStudent(this.stud).subscribe((data:boolean)=>{alert(data);
        if(data==true)
        {
          alert('Registration Successful');
        }
      });
    }
  });



 


}



}
